version: '3.7'

x-logging:
    &json-logging
    driver: json-file
    options:
        max-size: "1m"
        max-file: "3"

services:
    armf:
        build:
            context: ./
            dockerfile: Dockerfile.armf
        image: custom-armf
        restart: always
        container_name: armf
        environment:
            - NODE_UID=1001
            - NODE_GID=117
        volumes:
            - ./armer/execute.sh:/home/armer/execute.sh:ro
            - ./armer/.bashrc:/home/armer/.bashrc
        logging: *json-logging

    arm64:
        build:
            context: ./
            dockerfile: Dockerfile.arm64
        image: custom-arm64
        restart: always
        container_name: arm64
        environment:
            - NODE_UID=1001
            - NODE_GID=117
        volumes:
            - ./armer/execute.sh:/home/armer/execute.sh:ro
            - ./armer/.bashrc:/home/armer/.bashrc
        logging: *json-logging
