version: '3.7'

x-logging:
    &json-logging
    driver: json-file
    options:
        max-size: "1m"
        max-file: "3"

services:
    armf:
        build:
            context: ./
            dockerfile: Dockerfile.armf
        image: custom-armf
        restart: always
        container_name: armf
        env_file:
            - ./envfile
        volumes:
            - ./armer/execute.sh:/home/armer/execute.sh:ro
            - ./armer/src:/home/armer/src
            - ./armer/.bashrc:/home/armer/.bashrc
        logging: *json-logging
